[tool.ruff]
# Line length (same as Black)
line-length = 88
 
[tool.ruff.lint]
# Enable rules:
# E: pycodestyle errors
# F: Pyflakes
# I: isort (sort imports)
# B: flake8-bugbear (common bugs)
# UP: pyupgrade (modernize syntax)
select = ["E", "F", "I", "B", "UP"]
 
# Ignore specific rules if necessary
ignore = ["E501", "UP007", "UP045"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends", "fastapi.Query", "fastapi.params.Query"]
